name: IRChouine tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Your beautiful code vs some scary tester
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build tests
        run: docker run --rm -v $(pwd):/workspace ghcr.io/vantavoids/critervoid:main make test

      - name: Run tests
        run: docker run --rm -v $(pwd):/workspace ghcr.io/vantavoids/critervoid:main make test_run
